spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(WgMncfCmoCj5mhZRNWFA9PUvBes3AkGy1gzgKylHaZmAKP2pKOu3tD62YsaDWIklMBXfawvnmuU5u7bV8C/4iDE6V03Ed/TD)
    username: ENC(49RyIyDBsjwtsVUdu7jBew==)
    password: ENC(ZQrEq+x62sHxv5Tju52Ty7cECr4mZea3)
    data-source-properties:
      rewriteBatchedStatements: true
    hikari:
      maximum-pool-size: 5
      pool-name: HikariPool-1