spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(3h5jryDe+uDNqBOSNo6+0GWRr5Vz2RlfLmM5ElEylU5BTg7rIPoTK2D8knuI8R1ycvNT7kBLQbBW2rTfff2D/PrEFXwsGJ6t)
    username: ENC(49RyIyDBsjwtsVUdu7jBew==)
    password: ENC(ZQrEq+x62sHxv5Tju52Ty7cECr4mZea3)
    data-source-properties:
      rewriteBatchedStatements: true
    hikari:
      maximum-pool-size: 5
      pool-name: HikariPool-1