spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(a24511OJKzMFth9xEpUkL+fWNe9YBz4vSVfMdq7dXLDgdmObgsWqye5FiIS9wZ0jdIgK9Vy80Opk01KuswZ8DlrXLsgbD0b5)
    username: ENC(49RyIyDBsjwtsVUdu7jBew==)
    password: ENC(ZQrEq+x62sHxv5Tju52Ty7cECr4mZea3)
    data-source-properties:
      rewriteBatchedStatements: true
    hikari:
      maximum-pool-size: 5
      pool-name: HikariPool-1